{% set name = "awkward" %}
{% set version = "0.12.11" %}
{% set build_number = 0 %}

package:
  name: {{ name }}_and_variants
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: b6a1afc63f2d622bd967a5d60fbb681b2d1cf26ba4def780ac974e0b5333869a
    folder: {{ name }}
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-numba/{{ name }}-numba-{{ version }}.tar.gz
    sha256: 4963c2ac57b2faf519f20b715e8c673e1229ae8c4984684f328ad2b0585bf141
    folder: {{ name }}-numba

build:
  number: {{ build_number }}
  noarch: python

# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
requirements:
  build:
    - python

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install {{ name }} --no-deps -vv"
      noarch: python
    requirements:
      build:
      host:
        - python
        - pip
        - pytest-runner
      run:
        - python
        - numpy >=1.13.1
    test:
      imports:
        - awkward

  - name: {{ name }}-numba
    version: {{ version }}
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install {{ name }}-numba --no-deps -vv"
      noarch: python
    requirements:
      build:
      host:
        - python
        - pip
        - pytest-runner
      run:
        - python
        - numba
        - awkward =={{ version }}
    test:
      imports:
        - awkward.numba

about:
  home: https://github.com/scikit-hep/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ name }}/LICENSE
  summary: 'Manipulate arrays of complex data structures as easily as Numpy.'
  dev_url: https://github.com/scikit-hep/{{ name }}

extra:
  recipe-maintainers:
    - chrisburr
    - jpivarski
