{% set name = "awkward" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: d856b4a166ae054363368aed2e4a44338fec069baa4242e7d567c8323ebcc1eb

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - pip
    - python
  run:
    - numpy >=1.13.1
    - python

test:
  imports:
    - awkward
    - awkward._connect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-1.0
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
