{% set name = "awkward" %}
{% set version = "0.8.12" %}
{% set build_number = 0 %}

package:
  name: {{ name }}_and_variants
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: bf222e8f71aa46fa1ad8cbcfdc8086750c5e8a8097e04b02b9cc4af8cf9e0c9d
    folder: {{ name }}
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-numba/{{ name }}-numba-{{ version }}.tar.gz
    sha256: e21c7f0f80c3adddb313c5982b00ab995a20aa85dd028db4cb9ccdb0a8f32c01
    folder: {{ name }}-numba

build:
  number: {{ build_number }}
  noarch: python

# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
requirements:
  build:
    - python

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install {{ name }} --no-deps -vv"
      noarch: python
    requirements:
      build:
      host:
        - python
        - pip
        - pytest-runner
      run:
        - python
        - numpy >=1.13.1
    test:
      imports:
        - awkward

  - name: {{ name }}-numba
    version: {{ version }}
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install {{ name }}-numba --no-deps -vv"
      noarch: python
    requirements:
      build:
      host:
        - python
        - pip
        - pytest-runner
      run:
        - python
        - numba
        - awkward =={{ version }}
    test:
      imports:
        - awkward.numba

about:
  home: https://github.com/scikit-hep/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ name }}/LICENSE
  summary: 'Manipulate arrays of complex data structures as easily as Numpy.'
  dev_url: https://github.com/scikit-hep/{{ name }}

extra:
  recipe-maintainers:
    - chrisburr
    - jpivarski
