{% set name = "awkward" %}
{% set version = "0.12.18" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 9b3df4f2be92ac7d16709f15769c97591f25f0442061f1a4cc8715feb268e45c
    folder: {{ name }}
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-numba/{{ name }}-numba-{{ version }}.tar.gz
    sha256: cd3560cf4c3295e8f2db1d0fef4b76dc0d39fd0573c14a6e4f8421023ded3308
    folder: {{ name }}-numba

build:
  number: {{ build_number }}
  noarch: python

# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
requirements:
  build:
    - python

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install {{ name }} --no-deps -vv"
      noarch: python
    requirements:
      build:
      host:
        - python
        - pip
        - pytest-runner
      run:
        - python
        - numpy >=1.13.1
    test:
      imports:
        - awkward

  - name: {{ name }}-numba
    version: {{ version }}
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install {{ name }}-numba --no-deps -vv"
      noarch: python
    requirements:
      build:
      host:
        - python
        - pip
        - pytest-runner
      run:
        - python
        - numba <0.46
        - awkward =={{ version }}
    test:
      imports:
        - awkward.numba

about:
  home: https://github.com/scikit-hep/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ name }}/LICENSE
  summary: 'Manipulate arrays of complex data structures as easily as Numpy.'
  dev_url: https://github.com/scikit-hep/{{ name }}

extra:
  recipe-maintainers:
    - chrisburr
    - jpivarski
