{% set name = "awkward" %}
{% set version = "0.12.19" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 8540931484d5aee20430ca30c46dba03745050acaf23eeee795f1620904ae2e8
    folder: {{ name }}
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-numba/{{ name }}-numba-{{ version }}.tar.gz
    sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    folder: {{ name }}-numba

build:
  number: {{ build_number }}
  noarch: python

# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install {{ name }} --no-deps -vv"
      noarch: python
    requirements:
      build:
      host:
        - python
        - pip
        - pytest-runner
      run:
        - python
        - numpy >=1.13.1
    test:
      imports:
        - awkward

  - name: {{ name }}-numba
    version: {{ version }}
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install {{ name }}-numba --no-deps -vv"
      noarch: python
    requirements:
      build:
      host:
        - python
        - pip
        - pytest-runner
      run:
        - python
        - numba <0.46
        - awkward =={{ version }}
    test:
      imports:
        - awkward.numba

about:
  home: https://github.com/scikit-hep/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ name }}/LICENSE
  summary: 'Manipulate arrays of complex data structures as easily as Numpy.'
  dev_url: https://github.com/scikit-hep/{{ name }}

extra:
  recipe-maintainers:
    - chrisburr
    - jpivarski
