{% set name = "awkward" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: 3468cb80cab51252a1936e5e593c7df4588ea0e18dcb6fb31e3d2913ba883928
  patches:
    - awkward-1.0.2-singlethread.patch

build:
  number: 0
  script:
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - pip
    - python
  run:
    - numpy >=1.13.1
    - python
    - setuptools

test:
  imports:
    - awkward
    - awkward._connect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-1.0
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
