travis:
  secure:
    BINSTAR_TOKEN: ch9XzPMJKvNchZUF1ymGtub0rCOu6zEnV2VO8U7JFIiGYwcokFcGbAPu9Z4kdam/SPtD5stDSXElaejwZ8A96N6+3AXteHOh4aBilRyT24I62hvvnvWE++li1eiQAyC+vL4j1XUjfEqrofaKa1MPnFFTPMz0y1ob0VzudYj8GXn+UtQ2a1mDWhEiQ7vc+Y2gHz1Nn6sveBDAEbZWBGMbQS1WXCCiWvbbLE1JlsC/PC5TXLYjdqGbXAzD49hTjDnR6xHN8rKV7HfGqgk713E31s2XZW7JwS3RiiPB68E2zXuaEupw40yk14T4WKi1QBji7CMz8SGjFNOFANTyFvif7EP1n7wnDsOC/HVusW2mI38VwYk+foeb9tt3I6FJAGPjIMqCCfVppcgPMG5IJKGvg2h/pv0C+XlDGbOxymcrwr6dRGTE0FOJ/ubvX+XCrfAsV6gOxPou3RWh/PJCYeIE8uBaQcoiu3PHZGtNOyfNuczYaayS/afBRVbOfRffR/FPWpz9MutA/9RSg2TWmPRScaACIwSN9bmZYfMj/QTupIEiYa0YxCxP0vZulLiU1Vu4Zu+IVA0AhRz6U3JY2yPvpWZ9KKhRnhOcFum9dKqhiFwBL/O4txw39f/DNfQlJFFMenoLCHYnh6byUJzk68aVWdmrH7GKZmXfr+XRkLDmj0A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
